In [1]:
import numpy as np

In [28]:
M=np.array([[36,30],[30,25]])

In [29]:
M

array([[36, 30],
       [30, 25]])

In [30]:
value,vektor=np.linalg.eig(M)

In [31]:
value

array([61.,  0.])

In [32]:
vektor

array([[ 0.76822128, -0.6401844 ],
       [ 0.6401844 ,  0.76822128]])

In [37]:
0.3*7.5


2.25