## Exercise
Calculate Sobel-derivatives of the image *smallimg* as defined in the next row. Calculate magnitude and direction of sobel gradient. At which position of the image appears the maximum magnitude of the gradient?

In [5]:
import numpy as np
from scipy import ndimage as ndi

In [6]:
smallimg=np.array([[1,5,6],[1,6,6],[6,6,1]])
smallimg

array([[1, 5, 6],
       [1, 6, 6],
       [6, 6, 1]])

In [7]:
imx = np.zeros(smallimg.shape,dtype=np.float64)
ndi.filters.sobel(smallimg,1,imx,mode="nearest")
imy = np.zeros(smallimg.shape,dtype=np.float64)
ndi.filters.sobel(smallimg,0,imy,mode="nearest")
print("Gradient in x-direction")
print(imx)
print("Gradient in y-direction")
print(imy)

Gradient in x-direction
[[ 17.  20.   3.]
 [ 14.  10.  -4.]
 [  5. -10. -15.]]
Gradient in y-direction
[[  1.   2.   1.]
 [ 16.   2. -14.]
 [ 15.   0. -15.]]


In [8]:
magnitude=np.sqrt(imx**2+imy**2)
print("Magnitude of Gradient:")
print(magnitude)

Magnitude of Gradient:
[[17.02938637 20.09975124  3.16227766]
 [21.26029163 10.19803903 14.56021978]
 [15.8113883  10.         21.21320344]]


In [9]:
direction =np.arctan(imy/imx)
print("Direction of Gradient:")
print(direction)

Direction of Gradient:
[[ 0.05875582  0.09966865  0.32175055]
 [ 0.85196633  0.19739556  1.29249667]
 [ 1.24904577 -0.          0.78539816]]
